### ISSUE TITLE
`celery-singleton` + `celery-brainstorm`: How can they operate together?

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#53]
https://github.com/steinitzu/celery-singleton's [`celery_batch.Singleton`](https://github.com/steinitzu/celery-singleton/blob/0.3.1/celery_singleton/singleton.py#L17-L149)'s `BaseTask` prevents a task with the same args from refiring.

What would a conglomeration with [`celery_batches.Batches`](https://github.com/clokep/celery-batches/blob/v0.6/celery_batches/__init__.py#L200-L316) potentially look like?

**Comment by tony** [comment]
@clokep worth enabling discussions and moving this as  conversation to there?

**Comment by clokep** [comment]
It *might* just work (™️) if you inherit from both (since [`Singleton` does just call `super().apply_async(...)` at some point](https://github.com/steinitzu/celery-singleton/blob/0.3.1/celery_singleton/singleton.py#L118-L128).

I think you would install both, then do:

```python
from celery_batches import BatchTask
from celery_singleton import Singleton

class BatchSingletonTask(Singleton, BatchTask):
	pass
```

And then use it on your tasks as normal.

(This is completely untested.)

**Comment by clokep** [comment]
I don't think there's anything else to do here so I'm going to close this.
