### ISSUE TITLE
Loosen celery version constraint?

### ISSUE THREAD

**Issue by tony** [clokep/celery-batches#76]
[Celery 5.3](https://docs.celeryq.dev/en/v5.3.0/changelog.html#version-5-3-0) is out as of June 6th, 2023 🎉 !

@clokep: Are you open to removing the `<5.3` constraint completely and publishing the `celery-batches` to PyPI with a version bump (e.g. `0.7.1`)? 

<details>

<summary>History</summary>

https://github.com/clokep/celery-batches/commit/f261a9030d60ccce26f9501440c834d452acbaf4#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R33

#36

</details>

<details>

<summary>Poetry constraint error when celery-batches @ 0.7.0 + celery 5.3.0</summary>

```
❯ poetry update celery
Updating dependencies
Resolving dependencies... (11.8s)

Because celery-batches (0.7) depends on celery (>=4.4,<5.3)
 and no versions of celery-batches match >0.7.0,<0.8.0, celery-batches (>=0.7.0,<0.8.0) requires celery (>=4.4,<5.3).
So, because eduflow depends on both celery (~5.3.0) and celery-batches (~0.7.0), version solving failed.
```

</details>

**Comment by clokep** [comment]
> @clokep: Are you open to removing the `<5.3` constraint completely and publishing the `celery-batches` to PyPI with a version bump (e.g. `0.7.1`)?

In the past Celery aggressively breaks backwards compatibility, additionally since celery-batches reaches pretty deep into Celery it can be easy to break from changes. I don't really want bugs reported for versions which celery-batches doesn't attempt to support. I usually attempt to test the release candidates, but failed to do that for Celery 5.3. I'll do a new release soon.

**Comment by clokep** [comment]
> I usually attempt to test the release candidates, but failed to do that for Celery 5.3.

Looks like I did partially do this a while ago in #68, but never did a release once the RCs of Celery came out. 👍
